//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollegeSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOOK
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BOOK()
        {
            this.BOOK_ISSUES = new HashSet<BOOK_ISSUES>();
        }
    
        public string title { get; set; }
        public string author_name { get; set; }
        public string publisher_name { get; set; }
        public string phone_number { get; set; }
        public string p_address { get; set; }
        public int book_copies { get; set; }
        public string ss_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BOOK_ISSUES> BOOK_ISSUES { get; set; }
    }
}
