//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollegeSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOOK_RETURN
    {
        public int id { get; set; }
        public int issue_id { get; set; }
        public string issue_date { get; set; }
    
        public virtual BOOK_ISSUES BOOK_ISSUES { get; set; }
    }
}
