//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollegeSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLASS_ROUTINES
    {
        public int id { get; set; }
        public string day { get; set; }
        public string subject_type { get; set; }
        public string classname { get; set; }
        public string section { get; set; }
        public string class_time { get; set; }
        public string teacher { get; set; }
    }
}
