//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollegeSystem
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CollegeDbC : DbContext
    {
        public CollegeDbC()
            : base("name=CollegeDbC")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ATTENDANCE> ATTENDANCEs { get; set; }
        public virtual DbSet<BOOK_ISSUES> BOOK_ISSUES { get; set; }
        public virtual DbSet<BOOK_RETURN> BOOK_RETURN { get; set; }
        public virtual DbSet<BOOK> BOOKS { get; set; }
        public virtual DbSet<CLASS_ROUTINES> CLASS_ROUTINES { get; set; }
        public virtual DbSet<CLASS> CLASSES { get; set; }
        public virtual DbSet<EXAM> EXAMS { get; set; }
        public virtual DbSet<EXPENS> EXPENSES { get; set; }
        public virtual DbSet<HOSTEL> HOSTELS { get; set; }
        public virtual DbSet<MARKSHEET> MARKSHEETs { get; set; }
        public virtual DbSet<NOTICE> NOTICEs { get; set; }
        public virtual DbSet<PACKAGE> PACKAGES { get; set; }
        public virtual DbSet<PARENT> PARENTS { get; set; }
        public virtual DbSet<PAYMENT> PAYMENTS { get; set; }
        public virtual DbSet<ROOM> ROOMS { get; set; }
        public virtual DbSet<SEATALLOT> SEATALLOTS { get; set; }
        public virtual DbSet<SEATVACANT> SEATVACANTS { get; set; }
        public virtual DbSet<SECTION> SECTIONS { get; set; }
        public virtual DbSet<STUDENT> STUDENTS { get; set; }
        public virtual DbSet<SUBJECT> SUBJECTS { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TEACHER> TEACHERS { get; set; }
        public virtual DbSet<USER> USERS { get; set; }
    }
}
