//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollegeSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXPENS
    {
        public int exp_id { get; set; }
        public string exp_name { get; set; }
        public string exp_date { get; set; }
        public string exp_type { get; set; }
        public string exp_phone { get; set; }
        public string exp_email { get; set; }
        public string exp_status { get; set; }
        public Nullable<int> exp_amount { get; set; }
    }
}
