//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollegeSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOTICE
    {
        public int id { get; set; }
        public string title { get; set; }
        public string detail { get; set; }
        public string posted_by { get; set; }
        public string post_date { get; set; }
    }
}
