//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollegeSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class PACKAGE
    {
        public int sno { get; set; }
        public string class_status { get; set; }
        public string year { get; set; }
        public string fee { get; set; }
        public string total_fee { get; set; }
    }
}
