//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollegeSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PARENT()
        {
            this.STUDENTS = new HashSet<STUDENT>();
        }
    
        public int parent_id { get; set; }
        public string father_name { get; set; }
        public string mother_name { get; set; }
        public string father_occupation { get; set; }
        public string mother_occupation { get; set; }
        public string phone_number { get; set; }
        public string nationality { get; set; }
        public string present_address { get; set; }
        public string permanent_address { get; set; }
        public string picture { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STUDENT> STUDENTS { get; set; }
    }
}
