//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollegeSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAYMENT
    {
        public int pay_id { get; set; }
        public string pay_name { get; set; }
        public string status { get; set; }
        public string payment_date { get; set; }
        public int std_id { get; set; }
        public double pay_amount { get; set; }
    
        public virtual STUDENT STUDENT { get; set; }
    }
}
