//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollegeSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEATALLOT
    {
        public int id { get; set; }
        public string room_number { get; set; }
        public string seat_number { get; set; }
        public int hostel_id { get; set; }
        public int std_id { get; set; }
    
        public virtual HOSTEL HOSTEL { get; set; }
        public virtual STUDENT STUDENT { get; set; }
    }
}
